name: Run the Code

on: [push,pull_request]

jobs:
    run-the-code:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install all the dependencies
          run: npm i
        - name: Build the code
          run: npm run build
        - name: Start the code
          run: npm start  